### ISSUE TITLE
After "brunch watch --server" Error in events.js:72

### ISSUE THREAD

**Issue by terehov** [oliverzy/process-engine.js#1]
Hi!

This library is exactly what I need. Unfortunately I can't get it running. 
I followed all steps in README, however ending in an Error: 

---

brunch watch --server
26 Mar 00:49:33 - info: application started on http://localhost:3000/

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

---

Any hints? 

cheers, 

Eugene

**Comment by sandip8600** [comment]
Hi all,
I have installed all components but, after running command `brunch watch --server`. I am still getting following error
`
02 Aug 15:03:36 - info: starting custom server
02 Aug 15:03:36 - info: custom server started, initializing watcher
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
  at exports._errnoException (util.js:870:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)
`

**Comment by SrMordred** [comment]
Same error as above.

**Comment by SrMordred** [comment]
OK, I figure it out. 
At least in my case is about windows paths. 
Or is about the my user name that have spaces on it, or is about the length of the path, so brunch did´nt understand nodemon, even if globally installed. 

So I installed nodemon on local project, and set the custom server command to :

`command : 'node node_modules\\nodemon\\bin\\nodemon.js server.js'`

And it solved for me.
